#!/usr/bin/python3.6

import numpy as np
import pandas as pd

# Load titanic.csv

def main():

    # Assume file in current directory
    filename = 'titanic.csv'

    df = pd.read_csv(filename, index_col='PassengerId')
    df.head().to_csv('x.csv')

    #print('Type:', type(df), 'Shape:', df.shape)

if __name__ == '__main__':
    main()
